'use client'

import ScrollReveal from '@/components/shared/ScrollReveal'

const PARAGRAPHS = [
  "Coréal Media didn't come from a naming exercise. It came from a sincere question, born out of curiosity at a very specific moment in time.",
  "We are living in an era where content is no longer created by humans alone and no longer generated by machines alone. We sit at the intersection. Human intuition on one side. Machine intelligence on the other.",
  "So instead of asking for a name, we started with meaning.",
  "We explored languages around co-creation, collaboration, reality versus performance, authenticity versus virality, human and AI synergy. And a single idea stood out: Co-Real.",
  "From there, the spelling and tone evolved to match the kind of brand we were building: premium, intelligent, global, creative-forward, bold and confident.",
  "That is how CoReal became Coréal. The accent was not decorative. It was deliberate. It softened the word and elevated it. It gave the name a timeless, almost editorial quality — like luxury and legacy brands. It nods to the lineage of global creative excellence while remaining modern, digital, and forward-leaning.",
]

export default function BrandStory() {
  return (
    <section className="bg-bg-secondary section-padding border-t border-border-subtle relative overflow-hidden">
      {/* Decorative quotation mark */}
      <div
        aria-hidden
        className="pointer-events-none absolute top-8 left-8 font-display text-text-primary select-none hidden md:block"
        style={{ fontSize: '18rem', lineHeight: 1, opacity: 0.04 }}
      >
        &ldquo;
      </div>

      <div className="container-site relative z-10">
        <div className="grid grid-cols-1 md:grid-cols-2 gap-12 lg:gap-20">
          {/* Left: label + headline + callout */}
          <div>
            <ScrollReveal>
              <p className="font-mono text-accent text-label-lg uppercase tracking-widest mb-4">
                Brand Origin
              </p>
              <h2 className="font-display text-display-lg text-text-primary mb-10">
                How Coréal Began
              </h2>
            </ScrollReveal>

            {/* Co-Real deconstruction */}
            <ScrollReveal delay={0.2}>
              <div className="bg-bg-card border border-border-subtle rounded-sm overflow-hidden">
                <div className="grid grid-cols-2 divide-x divide-border-subtle">
                  <div className="p-6">
                    <p className="font-mono text-accent text-label-lg uppercase tracking-widest mb-2">Co</p>
                    <p className="font-display text-[1.5rem] text-text-primary mb-2">Collaboration</p>
                    <p className="font-body text-body-sm text-text-secondary">
                      Co-creation, collective intelligence, the power of working together.
                    </p>
                  </div>
                  <div className="p-6">
                    <p className="font-mono text-accent text-label-lg uppercase tracking-widest mb-2">Real</p>
                    <p className="font-display text-[1.5rem] text-text-primary mb-2">Authenticity</p>
                    <p className="font-body text-body-sm text-text-secondary">
                      Emotion, human truth, brand integrity that people actually feel.
                    </p>
                  </div>
                </div>
              </div>
            </ScrollReveal>
          </div>

          {/* Right: body paragraphs */}
          <div className="space-y-5">
            {PARAGRAPHS.map((para, i) => (
              <ScrollReveal key={i} delay={i * 0.08}>
                <p className="font-body text-body-md text-text-secondary leading-relaxed">
                  {para}
                </p>
              </ScrollReveal>
            ))}
          </div>
        </div>
      </div>
    </section>
  )
}
